In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_Projects/House_Price_Prediction/train.csv')
test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_Projects/House_Price_Prediction/test.csv')

In [ ]:
df.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [ ]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [ ]:
df=df.drop(['Alley','MiscFeature','Fence','PoolQC'],axis=1)
test=test.drop(['Alley','MiscFeature','Fence','PoolQC'],axis=1)

### **Choosing Features-From Problem statement pdf**


The dataset contains detailed information about residential houses, including:
* Property Features: Lot area, number of rooms, number of bathrooms, year built
* Location Features: Neighborhood, zoning classification
* Structural Features: Basement, garage, overall quality, overall condition
* Target Variable: SalePrice
---
1. LotArea
2. TotRmsAbvGrd, Bedroom, Kitchen
3. TotalBath = FullBath + 0.5 * HalfBath + BsmtFullBath + 0.5 * BsmtHalfBath
4. HouseAge= YrSold - YearBuilt
5. RemodAge=YrSold - YearRemodAdd
5. Neighborhood
6. MSZoning
7. BsmtQual, BsmtCond, TotalBsmtSF
8. GarageArea, GarageQual, GarageCond
7. GrLivArea
8. SaleType
9. SaleCondition
10. HouseAge= YrSold - YearBuilt
11. TotalConstructionArea = TotalBsmtSF + 1stFlrSF + 2ndFlrSF
12. TotalPorch = OpenPorchSF + EnclosedPorch + ScreenPorch + 3SsnPorch

In [ ]:
df=df[['LotArea','TotRmsAbvGrd','BedroomAbvGr','KitchenAbvGr','FullBath','HalfBath','BsmtFullBath','BsmtHalfBath','YrSold','YearRemodAdd','Neighborhood','MSZoning','BsmtQual', 'BsmtCond', 'TotalBsmtSF','GarageArea', 'GarageQual', 'GarageCond','GrLivArea','SaleType','SaleCondition','YrSold', 'YearBuilt', 'TotalBsmtSF' , '1stFlrSF' , '2ndFlrSF','OpenPorchSF', 'EnclosedPorch', 'ScreenPorch', '3SsnPorch','SalePrice']]
test=test[['LotArea','TotRmsAbvGrd','BedroomAbvGr','KitchenAbvGr','FullBath','HalfBath','BsmtFullBath','BsmtHalfBath','YrSold','YearRemodAdd','Neighborhood','MSZoning','BsmtQual', 'BsmtCond', 'TotalBsmtSF','GarageArea', 'GarageQual', 'GarageCond','GrLivArea','SaleType','SaleCondition','YrSold', 'YearBuilt', 'TotalBsmtSF' , '1stFlrSF' , '2ndFlrSF','OpenPorchSF', 'EnclosedPorch', 'ScreenPorch', '3SsnPorch']]

In [ ]:
df.shape

(1460, 31)

In [ ]:
df.isnull().sum()

LotArea           0
TotRmsAbvGrd      0
BedroomAbvGr      0
KitchenAbvGr      0
FullBath          0
HalfBath          0
BsmtFullBath      0
BsmtHalfBath      0
YrSold            0
YearRemodAdd      0
Neighborhood      0
MSZoning          0
BsmtQual         37
BsmtCond         37
TotalBsmtSF       0
GarageArea        0
GarageQual       81
GarageCond       81
GrLivArea         0
SaleType          0
SaleCondition     0
YrSold            0
YearBuilt         0
TotalBsmtSF       0
1stFlrSF          0
2ndFlrSF          0
OpenPorchSF       0
EnclosedPorch     0
ScreenPorch       0
3SsnPorch         0
SalePrice         0
dtype: int64

In [ ]:
test.isnull().sum()

LotArea           0
TotRmsAbvGrd      0
BedroomAbvGr      0
KitchenAbvGr      0
FullBath          0
HalfBath          0
BsmtFullBath      2
BsmtHalfBath      2
YrSold            0
YearRemodAdd      0
Neighborhood      0
MSZoning          4
BsmtQual         44
BsmtCond         45
TotalBsmtSF       1
GarageArea        1
GarageQual       78
GarageCond       78
GrLivArea         0
SaleType          1
SaleCondition     0
YrSold            0
YearBuilt         0
TotalBsmtSF       1
1stFlrSF          0
2ndFlrSF          0
OpenPorchSF       0
EnclosedPorch     0
ScreenPorch       0
3SsnPorch         0
dtype: int64

In [ ]:
df=df.loc[:, df.columns.duplicated()==False]
test=test.loc[:, test.columns.duplicated()==False]

In [ ]:
for i in df.columns:
  if df[i].dtype=='object':
    df[i]=df[i].fillna(df[i].mode()[0])
  else:
    df[i]=df[i].fillna(df[i].median())

for i in test.columns:
  if test[i].dtype=='object':
    test[i]=test[i].fillna(test[i].mode()[0])
  else:
    test[i]=test[i].fillna(test[i].median())

In [ ]:
df.isnull().sum()

LotArea          0
TotRmsAbvGrd     0
BedroomAbvGr     0
KitchenAbvGr     0
FullBath         0
HalfBath         0
BsmtFullBath     0
BsmtHalfBath     0
YrSold           0
YearRemodAdd     0
Neighborhood     0
MSZoning         0
BsmtQual         0
BsmtCond         0
TotalBsmtSF      0
GarageArea       0
GarageQual       0
GarageCond       0
GrLivArea        0
SaleType         0
SaleCondition    0
YearBuilt        0
1stFlrSF         0
2ndFlrSF         0
OpenPorchSF      0
EnclosedPorch    0
ScreenPorch      0
3SsnPorch        0
SalePrice        0
dtype: int64

In [ ]:
test.isnull().sum()

LotArea          0
TotRmsAbvGrd     0
BedroomAbvGr     0
KitchenAbvGr     0
FullBath         0
HalfBath         0
BsmtFullBath     0
BsmtHalfBath     0
YrSold           0
YearRemodAdd     0
Neighborhood     0
MSZoning         0
BsmtQual         0
BsmtCond         0
TotalBsmtSF      0
GarageArea       0
GarageQual       0
GarageCond       0
GrLivArea        0
SaleType         0
SaleCondition    0
YearBuilt        0
1stFlrSF         0
2ndFlrSF         0
OpenPorchSF      0
EnclosedPorch    0
ScreenPorch      0
3SsnPorch        0
dtype: int64

In [ ]:
x=df[['LotArea','TotRmsAbvGrd','BedroomAbvGr','KitchenAbvGr','Neighborhood','MSZoning','BsmtQual', 'BsmtCond', 'TotalBsmtSF','GarageArea', 'GarageQual', 'GarageCond','GrLivArea','SaleType','SaleCondition']]
y=df['SalePrice']

In [ ]:
x=x.loc[:, x.columns.duplicated()==False]

In [ ]:
x['HouseAge']=df['YrSold']-df['YearBuilt']
x['TotalConstructionArea']=df['TotalBsmtSF']+df['1stFlrSF'] + df['2ndFlrSF']
x['TotalPorch']=df['OpenPorchSF']+df['EnclosedPorch']+df['ScreenPorch']+df['3SsnPorch']
x['RemodAge']=df['YrSold']-df['YearRemodAdd']
x['TotalBath']=df['FullBath']+0.5*df['HalfBath']+df['BsmtFullBath']+0.5*df['BsmtHalfBath']

In [ ]:
x.shape

(1460, 20)

In [ ]:
x.head(2)

,LotArea,TotRmsAbvGrd,BedroomAbvGr,KitchenAbvGr,Neighborhood,MSZoning,BsmtQual,BsmtCond,TotalBsmtSF,GarageArea,GarageQual,GarageCond,GrLivArea,SaleType,SaleCondition,HouseAge,TotalConstructionArea,TotalPorch,RemodAge,TotalBath
0,8450,8,3,1,CollgCr,RL,Gd,TA,856,548,TA,TA,1710,WD,Normal,5,2566,61,5,3.5
1,9600,6,3,1,Veenker,RL,Gd,TA,1262,460,TA,TA,1262,WD,Normal,31,2524,0,31,2.5

In [ ]:
test['HouseAge']=test['YrSold']-test['YearBuilt']
test['TotalConstructionArea']=test['TotalBsmtSF']+test['1stFlrSF'] + test['2ndFlrSF']
test['TotalPorch']=test['OpenPorchSF']+test['EnclosedPorch']+test['ScreenPorch']+test['3SsnPorch']
test['RemodAge']=test['YrSold']-test['YearRemodAdd']
test['TotalBath']=test['FullBath']+0.5*test['HalfBath']+test['BsmtFullBath']+0.5*test['BsmtHalfBath']

In [ ]:
test=test[['LotArea','TotRmsAbvGrd','BedroomAbvGr','KitchenAbvGr','Neighborhood','MSZoning','BsmtQual', 'BsmtCond', 'TotalBsmtSF','GarageArea', 'GarageQual', 'GarageCond','GrLivArea','SaleType','SaleCondition','HouseAge','TotalConstructionArea','TotalPorch','RemodAge','TotalBath']]

In [ ]:
test.shape

(1459, 20)

In [ ]:
test.head(2)

,LotArea,TotRmsAbvGrd,BedroomAbvGr,KitchenAbvGr,Neighborhood,MSZoning,BsmtQual,BsmtCond,TotalBsmtSF,GarageArea,GarageQual,GarageCond,GrLivArea,SaleType,SaleCondition,HouseAge,TotalConstructionArea,TotalPorch,RemodAge,TotalBath
0,11622,5,2,1,NAmes,RH,TA,TA,882.0,730.0,TA,TA,896,WD,Normal,49,1778.0,120,49,1.0
1,14267,6,3,1,NAmes,RL,TA,TA,1329.0,312.0,TA,TA,1329,WD,Normal,52,2658.0,36,52,1.5

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
categorical_features=[i for i in x.columns if x[i].dtype=='O']
len(categorical_features)

8

In [ ]:
numerical_features=[i for i in x.columns if x[i].dtype!='O']
len(numerical_features)

12

In [ ]:
numerical_features

['LotArea',
 'TotRmsAbvGrd',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotalBsmtSF',
 'GarageArea',
 'GrLivArea',
 'HouseAge',
 'TotalConstructionArea',
 'TotalPorch',
 'RemodAge',
 'TotalBath']

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",categorical_transformer,categorical_features),
        ("StandardScalar",numerical_transformer,numerical_features)
    ]
)

In [ ]:
x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

models = {
    "Linear": LinearRegression(),
    "RF": RandomForestRegressor(),
    "KNN": KNeighborsRegressor()
}

In [ ]:
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(x_train,y_train)

  y_train_pred=model.predict(x_train)
  y_test_pred=model.predict(x_test)

  mse_train = mean_squared_error(y_train, y_train_pred)
  mse_test = mean_squared_error(y_test, y_test_pred)


  print(model)
  print("Training Accuracy")
  print('mae:',mean_absolute_error(y_train, y_train_pred))
  print('mse:' , mse_train)
  print('rmse:' , np.sqrt(mse_train))
  print('r2:' , r2_score(y_train, y_train_pred))
  print()

  print(model)
  print("Testing Accuracy")
  print('mae:',mean_absolute_error(y_test, y_test_pred))
  print('mse:' , mse_test)
  print('rmse:' , np.sqrt(mse_test))
  print('r2:' , r2_score(y_test, y_test_pred))
  print()

LinearRegression()
Training Accuracy
mae: 19116.105109767923
mse: 976602715.6285154
rmse: 31250.643443431934
r2: 0.8362654930469222

LinearRegression()
Testing Accuracy
mae: 21029.09367763337
mse: 1231369955.0844226
rmse: 35090.881366594695
r2: 0.8394631568693096

RandomForestRegressor()
Training Accuracy
mae: 7071.2613270547945
mse: 133754271.83469099
rmse: 11565.218192264727
r2: 0.9775751291684391

RandomForestRegressor()
Testing Accuracy
mae: 19827.477694063928
mse: 1046225801.5189523
rmse: 32345.41391787949
r2: 0.8636008726019195

KNeighborsRegressor()
Training Accuracy
mae: 16623.768493150685
mse: 731524496.0849316
rmse: 27046.70952417191
r2: 0.8773546286798103

KNeighborsRegressor()
Testing Accuracy
mae: 21409.512328767123
mse: 1162556532.5865755
rmse: 34096.283266458464
r2: 0.8484345383515429

## **The best results are given by Random Forest Regressor so we will fine tune it further.**

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params={
    "n_estimators": [100,200],
    "max_depth": [10,20,None],
    "min_samples_split": [2,5,10],
    "min_samples_leaf": [1,2,4]
}

In [ ]:
model=RandomForestRegressor()

In [ ]:
grid=GridSearchCV(estimator=model,param_grid=params,cv=5,scoring='r2',n_jobs=-1)

In [ ]:
grid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200]},
             scoring='r2')

In [ ]:
grid.best_score_

np.float64(0.8310237650929114)

In [ ]:
grid.best_params_

{'max_depth': None,
 'min_samples_leaf': 4,
 'min_samples_split': 5,
 'n_estimators': 100}

In [ ]:
best_model = grid.best_estimator_

In [ ]:
y_train_pred=best_model.predict(x_train)
print("Training")
print("MAE:", mean_absolute_error(y_train_pred, y_train))
print("MSE:", mean_squared_error(y_train_pred, y_train))
print("RMSE:", np.sqrt(mean_squared_error(y_train_pred, y_train)))
print("R2:", r2_score(y_train_pred, y_train))

y_test_pred=best_model.predict(x_test)
print("Testing")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

Training
MAE: 11871.95466229418
MSE: 439277997.87478095
RMSE: 20958.959847157992
R2: 0.9129006581346777
Testing
MAE: 19938.93335802188
MSE: 1055142144.6170532
RMSE: 32482.951599524527
R2: 0.8624384262003901

### We selected random forest regressor because it was having best r2 score. Then we have done Grid Search CV hyperparameter tunning. But the change in test r2 score is very less.